name: Deploy to Hostinger

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ðŸŸ¢ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: ðŸ” Localizar projeto e fazer Build
        id: build_step
        run: |
          # Procura a pasta que contÃ©m o package.json
          PROJECT_PATH=$(find . -name package.json -not -path "*/node_modules/*" -exec dirname {} \;)
          echo "Projeto encontrado em: $PROJECT_PATH"
          
          cd "$PROJECT_PATH"
          npm install
          npm run build
          echo "dist_path=$PROJECT_PATH/dist/" >> $GITHUB_OUTPUT

      - name: ðŸš€ Enviar para Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOSTINGER_FTP_HOST }}
          username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          local-dir: ${{ steps.build_step.outputs.dist_path }}
          server-dir: /home/u975902304/domains/tabelaplanosaude.com.br/public_html/
          state-name: .ftp-deploy-sync-state.json